# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ca931ce323f3b7cc5dfb57f7f14564d55e057361ee6dcd5b4c97bbcedfbf7fbafe8a0681c4d57fc666e7ed314ebcb35d1bcd2d59b7b77df28262a4f843f91a7

test:
  secret_key_base: 8cbc3c768149d417fda8c3b046594620688fbcaa46a5b6efec1fcf8cd2d06d3bd56a9e2b2a2b798520ddb2824f9228d092093655ad800fa3933754fac2b96651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
